# Generated by Django 4.2.25 on 2025-11-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary_id', models.CharField(max_length=50, unique=True)),
                ('overall_status', models.CharField(default='Planned', max_length=50)),
                ('total_cost_estimate', models.FloatField(blank=True, null=True)),
                ('total_duration_days', models.IntegerField(blank=True, null=True)),
                ('client_project_name', models.CharField(max_length=200)),
                ('expense_limit', models.FloatField(blank=True, null=True)),
                ('purpose_code', models.CharField(max_length=20)),
                ('approval_required', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationalTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary_id', models.CharField(max_length=50, unique=True)),
                ('overall_status', models.CharField(default='Planned', max_length=50)),
                ('total_cost_estimate', models.FloatField(blank=True, null=True)),
                ('total_duration_days', models.IntegerField(blank=True, null=True)),
                ('institution', models.CharField(max_length=200)),
                ('course_reference', models.CharField(max_length=50)),
                ('credit_hours', models.IntegerField(blank=True, null=True)),
                ('required_documentation', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeisureTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary_id', models.CharField(max_length=50, unique=True)),
                ('overall_status', models.CharField(default='Planned', max_length=50)),
                ('total_cost_estimate', models.FloatField(blank=True, null=True)),
                ('total_duration_days', models.IntegerField(blank=True, null=True)),
                ('activity_type', models.CharField(max_length=100)),
                ('accommodation', models.CharField(blank=True, max_length=200, null=True)),
                ('budget_per_day', models.FloatField(blank=True, null=True)),
                ('group_size', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
