# Generated by Django 5.2.7 on 2025-11-01 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_line_number', models.CharField(max_length=50, unique=True)),
                ('transport_capacity', models.IntegerField(blank=True, null=True)),
                ('transport_speed', models.FloatField(blank=True, null=True)),
                ('transport_frequency', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('number_of_employees', models.IntegerField(blank=True, null=True)),
                ('headquarters_location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=255)),
                ('station_location', models.CharField(blank=True, max_length=255, null=True)),
                ('station_accessibility', models.BooleanField(default=False)),
                ('connected_to', models.ManyToManyField(blank=True, to='transport_app.station')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255, unique=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.CharField(max_length=50, unique=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('route_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport_app.transport')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
            },
            bases=('transport_app.transport',),
        ),
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport_app.transport')),
            ],
            options={
                'verbose_name': 'Metro',
                'verbose_name_plural': 'Metros',
            },
            bases=('transport_app.transport',),
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport_app.transport')),
            ],
            options={
                'verbose_name': 'Train',
                'verbose_name_plural': 'Trains',
            },
            bases=('transport_app.transport',),
        ),
        migrations.CreateModel(
            name='Tram',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport_app.transport')),
            ],
            options={
                'verbose_name': 'Tram',
                'verbose_name_plural': 'Trams',
            },
            bases=('transport_app.transport',),
        ),
        migrations.CreateModel(
            name='BusCompany',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport_app.company')),
                ('number_of_bus_lines', models.IntegerField(blank=True, null=True)),
                ('average_bus_age', models.FloatField(blank=True, null=True)),
                ('ticket_price', models.FloatField(blank=True, null=True)),
                ('eco_friendly_fleet', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Bus Company',
                'verbose_name_plural': 'Bus Companies',
            },
            bases=('transport_app.company',),
        ),
        migrations.CreateModel(
            name='MetroCompany',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport_app.company')),
                ('number_of_lines', models.IntegerField(blank=True, null=True)),
                ('total_track_length', models.FloatField(blank=True, null=True)),
                ('automation_level', models.CharField(blank=True, max_length=255, null=True)),
                ('daily_passengers', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Metro Company',
                'verbose_name_plural': 'Metro Companies',
            },
            bases=('transport_app.company',),
        ),
        migrations.AddField(
            model_name='transport',
            name='operated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_operated', to='transport_app.company'),
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('station_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport_app.station')),
            ],
            options={
                'verbose_name': 'Bus Stop',
                'proxy': False,
            },
            bases=('transport_app.station',),
        ),
        migrations.CreateModel(
            name='MetroStation',
            fields=[
                ('station_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport_app.station')),
            ],
            options={
                'verbose_name': 'Metro Station',
                'proxy': False,
            },
            bases=('transport_app.station',),
        ),
        migrations.CreateModel(
            name='TrainStation',
            fields=[
                ('station_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport_app.station')),
            ],
            options={
                'verbose_name': 'Train Station',
                'proxy': False,
            },
            bases=('transport_app.station',),
        ),
        migrations.CreateModel(
            name='TramStation',
            fields=[
                ('station_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport_app.station')),
            ],
            options={
                'verbose_name': 'Tram Station',
                'proxy': False,
            },
            bases=('transport_app.station',),
        ),
        migrations.AddField(
            model_name='transport',
            name='arrives_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_arrivals', to='transport_app.station'),
        ),
        migrations.AddField(
            model_name='transport',
            name='departs_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_departures', to='transport_app.station'),
        ),
        migrations.AddField(
            model_name='transport',
            name='operates_in',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_transports', to='transport_app.city'),
        ),
        migrations.AddField(
            model_name='station',
            name='located_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='transport_app.city'),
        ),
        migrations.AddField(
            model_name='company',
            name='based_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='transport_app.city'),
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('schedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport_app.schedule')),
                ('first_run_time', models.TimeField(blank=True, null=True)),
                ('last_run_time', models.TimeField(blank=True, null=True)),
                ('frequency_minutes', models.IntegerField(blank=True, null=True)),
                ('day_of_week_mask', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Daily Schedule',
            },
            bases=('transport_app.schedule',),
        ),
        migrations.AddField(
            model_name='transport',
            name='applies_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_schedules', to='transport_app.schedule'),
        ),
        migrations.AddConstraint(
            model_name='station',
            constraint=models.UniqueConstraint(fields=('station_name', 'located_in'), name='unique_station_per_city'),
        ),
    ]
