# Generated by Django 5.0.7 on 2025-11-02 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_id', models.CharField(help_text='Identifiant unique de la personne', max_length=50, unique=True)),
                ('has_name', models.CharField(help_text='Nom de la personne', max_length=255)),
                ('has_age', models.IntegerField(blank=True, help_text='Âge de la personne', null=True)),
                ('has_email', models.EmailField(blank=True, help_text='Email de la personne', max_length=254, null=True)),
                ('has_phone_number', models.CharField(blank=True, help_text='Numéro de téléphone', max_length=20, null=True)),
                ('has_role', models.CharField(blank=True, help_text='Rôle de la personne', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='Contrôleur',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport_app.person')),
                ('has_badge_id', models.CharField(blank=True, help_text='Numéro de badge', max_length=50, null=True)),
                ('has_assigned_zone', models.CharField(blank=True, help_text='Zone assignée', max_length=100, null=True)),
                ('has_inspection_count', models.IntegerField(blank=True, default=0, help_text="Nombre d'inspections", null=True)),
                ('works_for_company', models.CharField(blank=True, help_text='Nom de la compagnie', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Contrôleur',
                'verbose_name_plural': 'Contrôleurs',
            },
            bases=('transport_app.person',),
        ),
        migrations.CreateModel(
            name='Passager',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport_app.person')),
                ('has_subscription_type', models.CharField(blank=True, help_text="Type d'abonnement (mensuel, hebdomadaire, etc.)", max_length=50, null=True)),
                ('has_preferred_transport', models.CharField(blank=True, help_text='Transport préféré (bus, métro, etc.)', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Passager',
                'verbose_name_plural': 'Passagers',
            },
            bases=('transport_app.person',),
        ),
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport_app.person')),
                ('has_license_number', models.CharField(blank=True, help_text='Numéro de permis', max_length=50, null=True)),
                ('has_experience_years', models.IntegerField(blank=True, help_text="Années d'expérience", null=True)),
                ('drives_line', models.CharField(blank=True, help_text='Ligne conduite', max_length=100, null=True)),
                ('has_work_shift', models.CharField(blank=True, help_text='Tranche horaire de travail', max_length=50, null=True)),
                ('works_for', models.ForeignKey(blank=True, help_text='Compagnie pour laquelle il travaille', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducteurs', to='transport_app.company')),
            ],
            options={
                'verbose_name': 'Conducteur',
                'verbose_name_plural': 'Conducteurs',
            },
            bases=('transport_app.person',),
        ),
        migrations.CreateModel(
            name='EmployéAgence',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport_app.person')),
                ('has_employee_id', models.CharField(blank=True, help_text="Numéro d'employé", max_length=50, null=True)),
                ('has_position', models.CharField(blank=True, help_text='Poste occupé', max_length=100, null=True)),
                ('works_at', models.CharField(blank=True, help_text='Lieu de travail', max_length=255, null=True)),
                ('has_schedule', models.ForeignKey(blank=True, help_text='Horaires de travail', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='transport_app.schedule')),
            ],
            options={
                'verbose_name': 'Employé Agence',
                'verbose_name_plural': 'Employés Agence',
            },
            bases=('transport_app.person',),
        ),
    ]
