# Generated by Django 4.2 on 2025-11-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('annual_revenue_musd', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
