# Generated by Django 5.0.7 on 2025-11-03 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport_app', '0002_person_contrôleur_passager_conducteur_employéagence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_ticket_id', models.CharField(help_text='Identifiant unique du ticket', max_length=50, unique=True)),
                ('has_price', models.FloatField(blank=True, help_text='Prix du ticket', null=True)),
                ('has_validity_duration', models.CharField(blank=True, help_text='Durée de validité', max_length=100, null=True)),
                ('has_purchase_date', models.DateField(blank=True, help_text="Date d'achat", null=True)),
                ('has_expiration_date', models.DateField(blank=True, help_text="Date d'expiration", null=True)),
                ('is_reduced_fare', models.BooleanField(default=False, help_text='Tarif réduit')),
                ('owned_by', models.ForeignKey(blank=True, help_text='Propriétaire du ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='transport_app.person')),
                ('valid_for', models.ForeignKey(blank=True, help_text='Transport pour lequel le ticket est valide', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valid_tickets', to='transport_app.transport')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='AbonnementHebdomadaire',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticket_app.ticket')),
                ('has_start_date', models.DateField(blank=True, help_text='Date de début', null=True)),
                ('has_end_date', models.DateField(blank=True, help_text='Date de fin', null=True)),
                ('has_zone_access', models.CharField(blank=True, help_text="Zone d'accès", max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Abonnement Hebdomadaire',
                'verbose_name_plural': 'Abonnements Hebdomadaires',
            },
            bases=('ticket_app.ticket',),
        ),
        migrations.CreateModel(
            name='AbonnementMensuel',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticket_app.ticket')),
                ('has_month', models.CharField(blank=True, help_text="Mois de l'abonnement", max_length=20, null=True)),
                ('has_auto_renewal', models.BooleanField(default=False, help_text='Renouvellement automatique')),
                ('has_payment_method', models.CharField(blank=True, help_text='Méthode de paiement', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Abonnement Mensuel',
                'verbose_name_plural': 'Abonnements Mensuels',
            },
            bases=('ticket_app.ticket',),
        ),
        migrations.CreateModel(
            name='TicketSenior',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticket_app.ticket')),
                ('has_age_condition', models.IntegerField(blank=True, help_text="Condition d'âge minimum", null=True)),
            ],
            options={
                'verbose_name': 'Ticket Senior',
                'verbose_name_plural': 'Tickets Senior',
            },
            bases=('ticket_app.ticket',),
        ),
        migrations.CreateModel(
            name='TicketSimple',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticket_app.ticket')),
                ('is_used', models.BooleanField(default=False, help_text='Ticket utilisé ou non')),
            ],
            options={
                'verbose_name': 'Ticket Simple',
                'verbose_name_plural': 'Tickets Simples',
            },
            bases=('ticket_app.ticket',),
        ),
        migrations.CreateModel(
            name='TicketÉtudiant',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticket_app.ticket')),
                ('has_institution_name', models.CharField(blank=True, help_text="Nom de l'institution", max_length=255, null=True)),
                ('has_student_id', models.CharField(blank=True, help_text="Numéro d'étudiant", max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Ticket Étudiant',
                'verbose_name_plural': 'Tickets Étudiant',
            },
            bases=('ticket_app.ticket',),
        ),
    ]
